comments:
  active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 100
  LongParameterList:
    active: true
    functionThreshold: 15
    constructorThreshold: 15
  TooManyFunctions:
    active: true
    thresholdInFiles: 40
    thresholdInClasses: 30
    thresholdInInterfaces: 25
    thresholdInObjects: 25
    thresholdInEnums: 20

empty-blocks:
  active: true

exceptions:
  active: true

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  ConstructorParameterNaming:
    active: true
  EnumNaming:
    active: true
    enumEntryPattern: '[A-Z][A-Za-z0-9]*'
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
  FunctionParameterNaming:
    active: true
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'
    propertyPattern: '[a-z][A-Za-z0-9]*'

performance:
  active: true

potential-bugs:
  active: true
  NullableToStringCall:
    active: false
  UnreachableCode:
    active: false

style:
  active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  DataClassShouldBeImmutable:
    active: false
  EqualsNullCall:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: false
  ExpressionBodySyntax:
    active: false
  ForbiddenComment:
    active: false
  ForbiddenImport:
    active: false
  MagicNumber:
    active: false
  BracesOnIfStatements:
    active: false
  MaxLineLength:
    active: false
  NoTabs:
    active: false
  OptionalUnit:
    active: false
  BracesOnWhenStatements:
    active: false
  PreferToOverPairSyntax:
    active: false
  ProtectedMemberInFinalClass:
    active: false
  SerialVersionUIDInSerializableClass:
    active: false
  SpacingBetweenPackageAndImports:
    active: false
  TrailingWhitespace:
    active: false
  UnderscoresInNumericLiterals:
    active: false
  UnusedPrivateMember:
    active: false
  UseArrayLiteralsInAnnotations:
    active: false
  UseDataClass:
    active: false
  UseIfInsteadOfWhen:
    active: false
  UseIsNullOrEmpty:
    active: true
  UseOrEmpty:
    active: false
  UselessCallOnNotNull:
    active: false
  UtilityClassWithPublicConstructor:
    active: true
  VarCouldBeVal:
    active: false
  WildcardImport:
    active: false
